enabled: true
ldapHost: {{ldap_host}}
ldapPort: {{ldap_port}}
use_tls: {{ldap_use_tls}}
bindDN: {{ldap_bind_dn}}
userSearchBase: {{ldap_user_search_base}}
userNameAttribute: {{ldap_user_name_attribute}}
userMailAttribute: {{ldap_user_mail_attribute}}
groupSearchBase: {{ldap_group_search_base}}
groupAttribute: {{ldap_group_attribute}}
origin: ldap
